### ISSUE TITLE
SC2 screen message during training

### ISSUE THREAD

**Issue by FadyaAbbas** [saizhang0218/VBC#8]
Hi, 
Can you please let me know how to get rid of or delete the message (CHEAT local player KillUnitTagBy..) that appears on the game screen during the training?
With many thanks
![SC2 message](https://user-images.githubusercontent.com/79666658/109339324-ba055700-7824-11eb-895b-91b9e1c62c2c.JPG)

**Comment by saizhang0218** [comment]
We dont have a clear answer for that. Please check with the original SMAC environment.
